/*
 * FILE : Pcap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1  (Final)
 * 
 * Portions Copyright (c) 1995-1997
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PERL 5 */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#undef free
#undef malloc
#include <string.h>
#ifdef __cplusplus
}
#endif
/* Definitions for compiling Perl extensions on a variety of machines */

#if defined(WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerl *pPerl = (CPerl *) this;
#define MAGIC_CAST   (int (CPerl::*)(SV *, MAGIC *))
#define SWIGCLASS_STATIC 
#else
#define MAGIC_PPERL
#define MAGIC_CAST
#define SWIGCLASS_STATIC static
#endif


/*****************************************************************************
 * $Header: /home/beazley/SWIG/SWIG1.1b3/swig_lib/perl5/RCS/perl5ptr.swg,v 1.1 1996/12/26 22:17:29 beazley Exp beazley $
 *
 * perl5ptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is only used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer.
 *
 * char * SWIG_GetPtr(SV *obj, void **ptr, char *type)
 *
 *      Gets a pointer value from a Perl5 scalar value.  If there is a 
 *      type-mismatch, returns a character string to the received type.  
 *      On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *
 * $Log: perl5ptr.swg,v $
 * Revision 1.1  1996/12/26 22:17:29  beazley
 * Initial revision
 *
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

/* These are internal variables.   Should be static */

typedef struct SwigPtrType {
  char               *name;
  int                 len;
  void               *(*cast)(void *);
  struct SwigPtrType *next;
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */
static int SwigStart[256];             /* Table containing starting positions    */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

#ifndef PERL_OBJECT
SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
#else
SWIGSTATIC
#define SWIG_RegisterMapping(a,b,c) _SWIG_RegisterMapping(pPerl, a,b,c)
void _SWIG_RegisterMapping(CPerl *pPerl, char *origtype, char *newtype, void *(*cast)(void *)) {
#endif

  int i;
  SwigPtrType *t = 0, *t1;

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc(SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }
  while (t->next) {
    if (strcmp(t->name,newtype) == 0) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;
  t->next = t1;
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGSTATIC 
char *SWIG_GetPtr(SV *sv, void **ptr, char *_t)
#else
SWIGSTATIC
#define SWIG_GetPtr(a,b,c) _SWIG_GetPtr(pPerl,a,b,c)
char *_SWIG_GetPtr(CPerl *pPerl, SV *sv, void **ptr, char *_t)
#endif
{
  char temp_type[256];
  char *name,*_c;
  int  len,i,start,end;
  IV   tmp;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    tmp = SvIV((SV*)SvRV(sv));
    if (!_t) {
      *(ptr) = (void *) tmp;
      return (char *) 0;
    }
  } else if (sv == &sv_undef) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return (char *) 0;
  } else if (SvTYPE(sv) == SVt_RV) {       /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return (char *) 0;
    else
      return "Not a valid pointer value";
  } else {                                 /* Don't know what it is */
      *(ptr) = (void *) 0;
      return "Not a valid pointer value";
  }
  if (_t) {
    /* Now see if the types match */      

    if (!sv_isa(sv,_t)) {
      _c = HvNAME(SvSTASH(SvRV(sv)));
      if (!SwigPtrSort) {
	qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort);  
	for (i = 0; i < 256; i++) {
	  SwigStart[i] = SwigPtrN;
	}
	for (i = SwigPtrN-1; i >= 0; i--) {
	  SwigStart[SwigPtrTable[i].name[0]] = i;
	}
	for (i = 255; i >= 1; i--) {
	  if (SwigStart[i-1] > SwigStart[i])
	    SwigStart[i-1] = SwigStart[i];
	}
	SwigPtrSort = 1;
	for (i = 0; i < SWIG_CACHESIZE; i++)  
	  SwigCache[i].stat = 0;
      }
      /* First check cache for matches.  Uses last cache value as starting point */
      cache = &SwigCache[SwigLastCache];
      for (i = 0; i < SWIG_CACHESIZE; i++) {
	if (cache->stat) {
	  if (strcmp(_t,cache->name) == 0) {
	    if (strcmp(_c,cache->mapped) == 0) {
	      cache->stat++;
	      *ptr = (void *) tmp;
	      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
	      return (char *) 0;
	    }
	  }
	}
	SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	if (!SwigLastCache) cache = SwigCache;
	else cache++;
      }

      start = SwigStart[_t[0]];
      end = SwigStart[_t[0]+1];
      sp = &SwigPtrTable[start];
      while (start < end) {
	if (swigcmp(_t,sp) == 0) break;
	sp++;
	start++;
      }
      if (start >= end) sp = 0;
      if (sp) {
	while (swigcmp(_t,sp) == 0) {
	  name = sp->name;
	  len = sp->len;
	  tp = sp->next;
	  while(tp) {
	    if (tp->len >= 255) {
	      return _c;
	    }
	    strncpy(temp_type,tp->name,255);
	    strncat(temp_type,_t+len,255-tp->len);
	    if (sv_isa(sv,temp_type)) {
	      /* Get pointer value */
	      *ptr = (void *) tmp;
	      if (tp->cast) *ptr = (*(tp->cast))(*ptr);

	      strcpy(SwigCache[SwigCacheIndex].mapped,_c);
	      strcpy(SwigCache[SwigCacheIndex].name,_t);
	      SwigCache[SwigCacheIndex].stat = 1;
	      SwigCache[SwigCacheIndex].tp = tp;
	      SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	      return (char *) 0;
	    }
	    tp = tp->next;
	  } 
	  /* Hmmm. Didn't find it this time */
 	  sp++;
	}
      }
      /* Didn't find any sort of match for this data.  
	 Get the pointer value and return the received type */
      *ptr = (void *) tmp;
      return _c;
    } else {
      /* Found a match on the first try.  Return pointer value */
      *ptr = (void *) tmp;
      return (char *) 0;
    }
  } 
  *ptr = (void *) tmp;
  return (char *) 0;
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr
/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerl *pPerl, SV *sv, char *name, int (CPerl::*set)(SV *, MAGIC *), int (CPerl::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = get;
  mg->mg_virtual->svt_set = set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}

#define SWIG_init    boot_Pcap

#define SWIG_name   "Net::Pcap::boot_Pcap"
#define SWIG_varinit "Net::Pcap::var_Pcap_init();"
#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
SWIGEXPORT(void,boot_Pcap)(CV* cv);
#else
SWIGEXPORT(void,boot_Pcap)(CPerl *, CV *cv);
#endif

#include "pcap.h"

/*
Create static data for the callback
*/
SV * perl_callback ;

void do_perl_callback (u_char * user, const struct pcap_pkthdr * h, const u_char * pkt )
    {
	SV * packet = newSVpv ((u_char *)pkt , h->caplen ) ;
	dSP ;
	PUSHMARK(sp) ;
	XPUSHs( (SV*) user ) ;
/*
	XPUSHs( newSViv (h->ts.tv_sec) ) ;
	XPUSHs( newSViv (h->ts.tv_usec) ) ;
*/
	XPUSHs( packet ) ;
	PUTBACK ;
	perl_call_sv ( perl_callback, G_DISCARD ) ;
	SvREFCNT_dec ( packet ) ;
    }
extern pcap_t *pcap_open_live(char *,int ,int ,int ,char *);
extern pcap_t *pcap_open_offline(char *,char *);
extern pcap_dumper_t *pcap_dump_open(pcap_t *,char *);
extern char *pcap_lookupdev(char *);
extern int pcap_lookupnet(char *,bpf_u_int32 *,bpf_u_int32 *,char *);
extern int pcap_dispatch(pcap_t *,int ,pcap_handler ,u_char *);
extern int pcap_loop(pcap_t *,int ,pcap_handler ,u_char *);
extern void pcap_dump(u_char *,const struct pcap_pkthdr *,const u_char *);
extern int pcap_compile(pcap_t *,struct bpf_program *,char *,int ,bpf_u_int32 );
extern int pcap_setfilter(pcap_t *,struct bpf_program *);
extern const u_char *pcap_next(pcap_t *,struct pcap_pkthdr *);
extern int pcap_datalink(pcap_t *);
extern int pcap_snapshot(pcap_t *);
extern int pcap_is_swapped(pcap_t *);
extern int pcap_major_version(pcap_t *);
extern int pcap_minor_version(pcap_t *);
extern int pcap_stats(pcap_t *,struct pcap_stat *);
extern FILE *pcap_file(pcap_t *);
extern int pcap_fileno(pcap_t *);
extern void pcap_perror(pcap_t *,char *);
extern char *pcap_geterr(pcap_t *);
extern char *pcap_strerror(int );
extern void pcap_close(pcap_t *);
extern void pcap_dump_close(pcap_dumper_t *);
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_Pcap_var::
class _wrap_Pcap_var : public CPerl {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

XS(_wrap_open_live) {

    pcap_t * _result;
    char * _arg0;
    int  _arg1;
    int  _arg2;
    int  _arg3;
    char * _arg4;
    int argvi = 0;
    SV * _saved[1];
    dXSARGS ;

    if ((items < 5) || (items > 5)) 
        croak("Usage: open_live(char *,int ,int ,int ,ebuf);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _arg3 = (int )SvIV(ST(3));
{
    if ( !SvROK( ST(4) ) )
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(4) , na ) ) ;
    }
    _arg4 = ( char * ) malloc ( PCAP_ERRBUF_SIZE ) ;
    _arg4[0] = '\0' ;
}
    _saved[0] = ST(4);
    _result = (pcap_t *)pcap_open_live(_arg0,_arg1,_arg2,_arg3,_arg4);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"pcap_tPtr", (void *) _result);
{
    if ( _arg4[0] != '\0' )
    {
        sv_setpvn( SvRV ( _saved[0] ) , _arg4 , PCAP_ERRBUF_SIZE ) ;
    }
    free ( _arg4 ) ;
}
    XSRETURN(argvi);
}

XS(_wrap_open_offline) {

    pcap_t * _result;
    char * _arg0;
    char * _arg1;
    int argvi = 0;
    SV * _saved[1];
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: open_offline(char *,ebuf);");
    _arg0 = (char *) SvPV(ST(0),na);
{
    if ( !SvROK( ST(1) ) )
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(1) , na ) ) ;
    }
    _arg1 = ( char * ) malloc ( PCAP_ERRBUF_SIZE ) ;
    _arg1[0] = '\0' ;
}
    _saved[0] = ST(1);
    _result = (pcap_t *)pcap_open_offline(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"pcap_tPtr", (void *) _result);
{
    if ( _arg1[0] != '\0' )
    {
        sv_setpvn( SvRV ( _saved[0] ) , _arg1 , PCAP_ERRBUF_SIZE ) ;
    }
    free ( _arg1 ) ;
}
    XSRETURN(argvi);
}

XS(_wrap_dump_open) {

    pcap_dumper_t * _result;
    pcap_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: dump_open(pcap_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of dump_open. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (pcap_dumper_t *)pcap_dump_open(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"pcap_dumper_tPtr", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_lookupdev) {

    char * _result;
    char * _arg0;
    int argvi = 0;
    SV * _saved[1];
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: lookupdev(ebuf);");
{
    if ( !SvROK( ST(0) ) )
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(0) , na ) ) ;
    }
    _arg0 = ( char * ) malloc ( PCAP_ERRBUF_SIZE ) ;
    _arg0[0] = '\0' ;
}
    _saved[0] = ST(0);
    _result = (char *)pcap_lookupdev(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
{
    if ( _arg0[0] != '\0' )
    {
        sv_setpvn( SvRV ( _saved[0] ) , _arg0 , PCAP_ERRBUF_SIZE ) ;
    }
    free ( _arg0 ) ;
}
    XSRETURN(argvi);
}

XS(_wrap_lookupnet) {

    int  _result;
    char * _arg0;
    bpf_u_int32 * _arg1;
    bpf_u_int32 * _arg2;
    char * _arg3;
    int argvi = 0;
    bpf_u_int32  temp_bpf;
    bpf_u_int32  temp_bpf0;
    SV * _saved[3];
    dXSARGS ;

    if ((items < 4) || (items > 4)) 
        croak("Usage: lookupnet(char *,bpf_u_int32 *,bpf_u_int32 *,ebuf);");
    _arg0 = (char *) SvPV(ST(0),na);
{
    if ( SvROK( ST(1) ) )
    {
	_arg1 = & temp_bpf ;
    }
    else
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(1) , na ) ) ;
    }
}
    _saved[0] = ST(1);
{
    if ( SvROK( ST(2) ) )
    {
	_arg2 = & temp_bpf0 ;
    }
    else
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(2) , na ) ) ;
    }
}
    _saved[1] = ST(2);
{
    if ( !SvROK( ST(3) ) )
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(3) , na ) ) ;
    }
    _arg3 = ( char * ) malloc ( PCAP_ERRBUF_SIZE ) ;
    _arg3[0] = '\0' ;
}
    _saved[2] = ST(3);
    _result = (int )pcap_lookupnet(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
{
    sv_setiv( SvRV ( _saved[0] ) , htonl ( *_arg1 ) ) ;
}
{
    sv_setiv( SvRV ( _saved[1] ) , htonl ( *_arg2 ) ) ;
}
{
    if ( _arg3[0] != '\0' )
    {
        sv_setpvn( SvRV ( _saved[2] ) , _arg3 , PCAP_ERRBUF_SIZE ) ;
    }
    free ( _arg3 ) ;
}
    XSRETURN(argvi);
}

XS(_wrap_dispatch) {

    int  _result;
    pcap_t * _arg0;
    int  _arg1;
    pcap_handler  _arg2;
    u_char * _arg3;
    int argvi = 0;
    dXSARGS ;

    if ((items < 4) || (items > 4)) 
        croak("Usage: dispatch(pcap_t *,int ,pcap_handler ,user);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of dispatch. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
{
    perl_callback=ST(2) ;
    _arg2=(pcap_handler)&do_perl_callback ;
}
{
    _arg3 = (unsigned char *) ST(3) ;
}
    _result = (int )pcap_dispatch(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_loop) {

    int  _result;
    pcap_t * _arg0;
    int  _arg1;
    pcap_handler  _arg2;
    u_char * _arg3;
    int argvi = 0;
    dXSARGS ;

    if ((items < 4) || (items > 4)) 
        croak("Usage: loop(pcap_t *,int ,pcap_handler ,user);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of loop. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
{
    perl_callback=ST(2) ;
    _arg2=(pcap_handler)&do_perl_callback ;
}
{
    _arg3 = (unsigned char *) ST(3) ;
}
    _result = (int )pcap_loop(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_dump) {

    u_char * _arg0;
    struct pcap_pkthdr * _arg1;
    u_char * _arg2;
    int argvi = 0;
    dXSARGS ;

    if ((items < 3) || (items > 3)) 
        croak("Usage: dump(user,struct pcap_pkthdr *,pkt);");
{
    _arg0 = (unsigned char *) ST(0) ;
}
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"struct pcap_pkthdrPtr")) {
        croak("Type error in argument 2 of dump. Expected struct pcap_pkthdrPtr.");
        XSRETURN(1);
    }
{
    _arg2 = (unsigned char *) ST(2) ;
}
    pcap_dump(_arg0,_arg1,_arg2);
    XSRETURN(argvi);
}

XS(_wrap_compile) {

    int  _result;
    pcap_t * _arg0;
    struct bpf_program * _arg1;
    char * _arg2;
    int  _arg3;
    bpf_u_int32  _arg4;
    int argvi = 0;
    dXSARGS ;

    if ((items < 5) || (items > 5)) 
        croak("Usage: compile(pcap_t *,empty,char *,int ,bpf_u_int32 );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of compile. Expected pcap_tPtr.");
        XSRETURN(1);
    }
{
    if ( !SvROK( ST(1) ) )
    {
	croak ( "Expected a reference (but got %X)" , SvPV ( ST(1) , na ) ) ;
    }
/*
Note we DON'T free the compiled bpf program anywhere. So it's a memory leak.
Sue me. How many filters were you planning to compile?
PRL 1-May-1997
*/
    _arg1 = (struct bpf_program*) malloc ( sizeof ( struct bpf_program ) ) ;
    sv_setref_pv(SvRV(ST(1)), "struct bpf_program" , (void * ) _arg1 ) ;
}
    _arg2 = (char *) SvPV(ST(2),na);
    _arg3 = (int )SvIV(ST(3));
{
    _arg4 = (bpf_u_int32 ) SvIV(ST(4)) ;
}
    _result = (int )pcap_compile(_arg0,_arg1,_arg2,_arg3,_arg4);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_setfilter) {

    int  _result;
    pcap_t * _arg0;
    struct bpf_program * _arg1;
    int argvi = 0;
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: setfilter(pcap_t *,compiled);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of setfilter. Expected pcap_tPtr.");
        XSRETURN(1);
    }
{
    if ( SWIG_GetPtr ( ST(1), ( void * * ) & _arg1 , "struct bpf_program" ) )
    {
	croak("Expected struct bpf_program.");
    }
}
    _result = (int )pcap_setfilter(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_next) {

    u_char * _result;
    pcap_t * _arg0;
    struct pcap_pkthdr * _arg1;
    int argvi = 0;
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: next(pcap_t *,struct pcap_pkthdr *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of next. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"struct pcap_pkthdrPtr")) {
        croak("Type error in argument 2 of next. Expected struct pcap_pkthdrPtr.");
        XSRETURN(1);
    }
    _result = (u_char *)pcap_next(_arg0,_arg1);
{
    sv_setpv (  ST(0) , _result ) ;
}
    XSRETURN(argvi);
}

XS(_wrap_datalink) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: datalink(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of datalink. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_datalink(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_snapshot) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: snapshot(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of snapshot. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_snapshot(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_is_swapped) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: is_swapped(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of is_swapped. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_is_swapped(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_major_version) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: major_version(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of major_version. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_major_version(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_minor_version) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: minor_version(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of minor_version. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_minor_version(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_stats) {

    int  _result;
    pcap_t * _arg0;
    struct pcap_stat * _arg1;
    int argvi = 0;
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: stats(pcap_t *,struct pcap_stat *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of stats. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"struct pcap_statPtr")) {
        croak("Type error in argument 2 of stats. Expected struct pcap_statPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_stats(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_file) {

    FILE * _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: file(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of file. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (FILE *)pcap_file(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"FILEPtr", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_fileno) {

    int  _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: fileno(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of fileno. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (int )pcap_fileno(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_perror) {

    pcap_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    if ((items < 2) || (items > 2)) 
        croak("Usage: perror(pcap_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of perror. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    pcap_perror(_arg0,_arg1);
    XSRETURN(argvi);
}

XS(_wrap_get_error) {

    char * _result;
    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: get_error(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of get_error. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    _result = (char *)pcap_geterr(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_strerror) {

    char * _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: strerror(int );");
    _arg0 = (int )SvIV(ST(0));
    _result = (char *)pcap_strerror(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_close) {

    pcap_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: close(pcap_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_tPtr")) {
        croak("Type error in argument 1 of close. Expected pcap_tPtr.");
        XSRETURN(1);
    }
    pcap_close(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_dumper) {

    pcap_dumper_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    if ((items < 1) || (items > 1)) 
        croak("Usage: dumper(pcap_dumper_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"pcap_dumper_tPtr")) {
        croak("Type error in argument 1 of dumper. Expected pcap_dumper_tPtr.");
        XSRETURN(1);
    }
    pcap_dump_close(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_perl5_Pcap_var_init) {
    dXSARGS;
    SV *sv;
    XSRETURN(1);
}
#ifdef __cplusplus
extern "C"
#endif
XS(boot_Net__Pcap) {
	 dXSARGS;
	 char *file = __FILE__;
	 newXS("Net::Pcap::var_Pcap_init", _wrap_perl5_Pcap_var_init, file);
	 newXS("Net::Pcap::open_live", _wrap_open_live, file);
	 newXS("Net::Pcap::open_offline", _wrap_open_offline, file);
	 newXS("Net::Pcap::dump_open", _wrap_dump_open, file);
	 newXS("Net::Pcap::lookupdev", _wrap_lookupdev, file);
	 newXS("Net::Pcap::lookupnet", _wrap_lookupnet, file);
	 newXS("Net::Pcap::dispatch", _wrap_dispatch, file);
	 newXS("Net::Pcap::loop", _wrap_loop, file);
	 newXS("Net::Pcap::dump", _wrap_dump, file);
	 newXS("Net::Pcap::compile", _wrap_compile, file);
	 newXS("Net::Pcap::setfilter", _wrap_setfilter, file);
	 newXS("Net::Pcap::next", _wrap_next, file);
	 newXS("Net::Pcap::datalink", _wrap_datalink, file);
	 newXS("Net::Pcap::snapshot", _wrap_snapshot, file);
	 newXS("Net::Pcap::is_swapped", _wrap_is_swapped, file);
	 newXS("Net::Pcap::major_version", _wrap_major_version, file);
	 newXS("Net::Pcap::minor_version", _wrap_minor_version, file);
	 newXS("Net::Pcap::stats", _wrap_stats, file);
	 newXS("Net::Pcap::file", _wrap_file, file);
	 newXS("Net::Pcap::fileno", _wrap_fileno, file);
	 newXS("Net::Pcap::perror", _wrap_perror, file);
	 newXS("Net::Pcap::get_error", _wrap_get_error, file);
	 newXS("Net::Pcap::strerror", _wrap_strerror, file);
	 newXS("Net::Pcap::close", _wrap_close, file);
	 newXS("Net::Pcap::dumper", _wrap_dumper, file);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("unsigned short","short",0);
	 SWIG_RegisterMapping("long","unsigned long",0);
	 SWIG_RegisterMapping("long","signed long",0);
	 SWIG_RegisterMapping("signed short","short",0);
	 SWIG_RegisterMapping("bpf_u_int32","unsigned int",0);
	 SWIG_RegisterMapping("bpf_u_int32","int",0);
	 SWIG_RegisterMapping("signed int","int",0);
	 SWIG_RegisterMapping("short","unsigned short",0);
	 SWIG_RegisterMapping("short","signed short",0);
	 SWIG_RegisterMapping("unsigned long","long",0);
	 SWIG_RegisterMapping("int","bpf_u_int32",0);
	 SWIG_RegisterMapping("int","unsigned int",0);
	 SWIG_RegisterMapping("int","signed int",0);
	 SWIG_RegisterMapping("unsigned int","bpf_u_int32",0);
	 SWIG_RegisterMapping("unsigned int","int",0);
	 SWIG_RegisterMapping("u_char","unsigned char",0);
	 SWIG_RegisterMapping("unsigned char","u_char",0);
	 SWIG_RegisterMapping("signed long","long",0);
	 ST(0) = &sv_yes;
	 XSRETURN(1);
}
