# This file was automatically generated by SWIG
package Net::Pcap;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Net::Pcap;
bootstrap Net::Pcap;
var_Pcap_init();
@EXPORT = qw( );
1;
